// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcVcL560bl4OwjTjRPrRNUL-EEHT05Eqg',
    appId: '1:266704213953:web:bbd15a6df2c8fff19c8140',
    messagingSenderId: '266704213953',
    projectId: 'nexus-90e55',
    authDomain: 'nexus-90e55.firebaseapp.com',
    databaseURL: 'https://nexus-90e55-default-rtdb.firebaseio.com',
    storageBucket: 'nexus-90e55.firebasestorage.app',
    measurementId: 'G-0HSYZG04QS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjvIK6ytNKulMyUeibBxaZa9lrFullVfI',
    appId: '1:266704213953:android:e4b3a7234984ac269c8140',
    messagingSenderId: '266704213953',
    projectId: 'nexus-90e55',
    storageBucket: 'nexus-90e55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2sks5jKWuOkohW8m3JNo4pU0zjaWKDws',
    appId: '1:266704213953:ios:8dfa19213c7c7baf9c8140',
    messagingSenderId: '266704213953',
    projectId: 'nexus-90e55',
    storageBucket: 'nexus-90e55.firebasestorage.app',
    iosClientId: '266704213953-jr8tjov25i1egrvps5m1m709ifuj2j3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.nexus',
  );
}
